version: '3.8'

services:
  db:
    image: postgres:16.4
    container_name: telegram_bot_db
    environment:
      POSTGRES_DB: telegram_bot
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - telegram_network

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram_bot_service
    environment:
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      POSTGRES_URL: ${POSTGRES_URL}
    depends_on:
      - db
    networks:
      - telegram_network

networks:
  telegram_network:
    driver: bridge

volumes:
  db_data:
